name: Pull events

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull events from relays
        run: curl -s -X GET "https://rococo-belekoy-885436.netlify.app/api/data/insert"
